<a href="https://colab.research.google.com/github/JoiceEmilly/Projeto_Ricardo/blob/main/Projeto_Ricardo_Roberto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Autora: Joice Emilly Nascimento da Silva

In [7]:
#Importacoes
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [ ]:
#Dataset de dados de validacao
dados_coracao = pd.read_csv("heart.csv", encoding="utf-8")

In [ ]:
#Atributos que serão treinados para gerar o modelo classificação
data_treino = np.array(dados_coracao[['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal']])
#Atributo de classificacao
data_classif = np.array(dados_coracao['target'])

In [ ]:
# Formato dos dados
dados_coracao.shape

In [ ]:
# Primeiras linhas do dataset
dados_coracao.head(5)

In [ ]:
# Ultimas linhas do dataset
dados_coracao.tail(5)

In [ ]:
# Correlação entre as variáveis e que não implica causalidade
def plot_corr(dados_coracao, size=10):
    corr = dados_coracao.corr()    
    fig, ax = plt.subplots(figsize = (size, size))
    ax.matshow(corr)  
    plt.xticks(range(len(corr.columns)), corr.columns) 
    plt.yticks(range(len(corr.columns)), corr.columns) 

In [ ]:
# Criação do gráfico
plot_corr(dados_coracao)

In [ ]:
# Spliting = 70% para dados de treino e 30% para dados de teste

In [ ]:
#Definição dos conjuntos de treinamento e validação
x_treino, x_val, y_treino, y_val = train_test_split(data_treino, data_classif, test_size=0.30)

In [ ]:
#Apresentacao dos dados selecionados para o conjunto de treinamento e validacao
print("-----------------------")
print("Conjunto de Treinamento")
print(x_treino)
print("Conjunto de Validacao")
print(x_val)
print("-----------------------")

-----------------------
Conjunto de Treinamento
[[41.  1.  1. ...  1.  0.  1.]
 [57.  0.  0. ...  1.  0.  3.]
 [60.  1.  0. ...  1.  2.  3.]
 ...
 [76.  0.  2. ...  1.  0.  2.]
 [54.  1.  1. ...  2.  1.  3.]
 [38.  1.  3. ...  1.  0.  3.]]
Conjunto de Validacao
[[59.  1.  2. ...  2.  0.  2.]
 [44.  1.  1. ...  2.  0.  2.]
 [65.  0.  2. ...  2.  1.  2.]
 ...
 [50.  0.  1. ...  2.  0.  2.]
 [52.  1.  1. ...  2.  0.  2.]
 [57.  1.  0. ...  1.  1.  1.]]
-----------------------


In [ ]:
# Resultados
print("{0:0.2f}% nos dados de treino".format((len(x_treino)/len(dados_coracao.index)) * 100))
print("{0:0.2f}% nos dados de teste".format((len(x_val)/len(dados_coracao.index)) * 100))

In [ ]:
# - Aplicando o Algoritmo com o Naive Bayes - GaussianNB.

In [ ]:
#Treinamento do modelo com os dados atribuidos ao conjunto de treinamento
modelo_NB = GaussianNB()
modelo_NB.fit(x_treino, y_treino)

GaussianNB()

In [ ]:
#Predição e acurácia para o conjunto de treinamento
print("Predicao para o conjunto de treinamento")
y_pred_treino = modelo_NB.predict(x_treino)
print("Acuracia para o conjunto de treinamento")
print(accuracy_score(y_treino, y_pred_treino))
print("Na Base de Treinamento")

Predicao para o conjunto de treinamento
Acuracia para o conjunto de treinamento
0.8207547169811321
Na Base de Treinamento


In [ ]:
#Predição e acurácia para o conjunto de validação
print("Predicao para o conjunto de validacao")
y_pred_val = modelo_NB.predict(x_val)
print("Acuracia para o conjunto de validacao")
print(accuracy_score(y_val, y_pred_val))
print("na Base de Teste")

Predicao para o conjunto de validacao
Acuracia para o conjunto de validacao
0.8791208791208791
na Base de Teste


In [ ]:
from sklearn import metrics

In [ ]:
# Métricas

In [ ]:
# Criando uma Confusion Matrix
print("Confusion Matrix")

print("{0}".format(metrics.confusion_matrix(y_val, y_pred_val, labels = [1, 0])))
print("")

print("Classification Report")
print(metrics.classification_report(y_val, y_pred_val, labels = [1, 0]))

Confusion Matrix
[[50  4]
 [ 7 30]]

Classification Report
              precision    recall  f1-score   support

           1       0.88      0.93      0.90        54
           0       0.88      0.81      0.85        37

    accuracy                           0.88        91
   macro avg       0.88      0.87      0.87        91
weighted avg       0.88      0.88      0.88        91



In [ ]:
# Criando uma Curva Roc
print("Roc Curve")

# Compute ROC curve and ROC area for each class
#fpr = dict()
#tpr = dict()
#roc_auc = dict()
#for i in range(y_pred_val):
#    fpr[i], tpr[i], _ = roc_curve(y_val, y_pred_val)
#    roc_auc[i] = auc(fpr[i], tpr[i])

# Compute micro-average ROC curve and ROC area
#fpr["micro"], tpr["micro"], _ = roc_curve(y_val.ravel(), y_score.ravel())
#roc_auc["micro"] = auc(fpr["micro"], tpr["micro"])

Roc Curve


In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
modelo_v2 = RandomForestClassifier(random_state = 42)
modelo_v2.fit(x_treino, y_treino.ravel())

RandomForestClassifier(random_state=42)

In [ ]:
# Verificação dos dados de treino
rf_predict_train = modelo_v2.predict(x_treino)
print("Exatidão (Accuracy): {0:.4f}".format(metrics.accuracy_score(y_treino, rf_predict_train)))

Exatidão (Accuracy): 1.0000


In [ ]:
# Verificação dos dados de teste
rf_predict_test = modelo_v2.predict(x_val)
print("Exatidão (Accuracy): na Base de Teste {0:.4f}".format(metrics.accuracy_score(y_val, rf_predict_test)))
print()

Exatidão (Accuracy): na Base de Teste 0.8901



In [ ]:
# Versionamento do Modelo com a Matrix de Confusão
print("Confusion Matrix")

print("{0}".format(metrics.confusion_matrix(y_val, rf_predict_test, labels = [1, 0])))
print("")

print("Classification Report")
print(metrics.classification_report(y_val, rf_predict_test, labels = [1, 0]))

Confusion Matrix
[[49  5]
 [ 5 32]]

Classification Report
              precision    recall  f1-score   support

           1       0.91      0.91      0.91        54
           0       0.86      0.86      0.86        37

    accuracy                           0.89        91
   macro avg       0.89      0.89      0.89        91
weighted avg       0.89      0.89      0.89        91



In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
# Versionamento do modelo usando Regressão Logística
modelo_v3 = LogisticRegression(C = 0.7, random_state = 42)
modelo_v3.fit(x_treino, y_treino.ravel())
lr_predict_test = modelo_v3.predict(x_val)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
